spring:
  # 접속 DB 설정
  datasource:
    url: jdbc:oracle://127.0.0.1:3306/heailngpill
    username: healingpill
    password: 123456
    driver-class-name: org.jdbc.driver.OracleDriver

mybatis:
  # mapper 경로 지정
  mapper-locations: query/**/*.xml
  configuration:
    map-underscore-to-camel-case: true